# A sample build_config.yaml to supply to Element Web's build pipeline,
# enabling custom functionality at compile time. Copy this file to
# `build_config.yaml` in the same directory to use, as you would with
# `config.json`.
#
# Note: The vast majority of users DO NOT need this. If you are looking
# to build your own Element Web as seen on app.element.io or similar then
# this is not required.
#
# This config file does become required if you are looking to add runtime
# functionality to Element Web, such as customisation endpoints and modules.
#
# Over time we might expand this config to better support some use cases.
# Watch the release notes for features which might impact this config.

#
# false => installer will perform checks to try to ensure correct versions of dependencies
# true => installer will skip dependency version checks.
# Enable skipping at your own peril, and manually ensure all modules reference/load the correct version
# of the extension module
#
# This may be useful during development due to limitations/incompatilibilities in "npm list ..."
#
skip_module_dependency_version_check: true

# The modules to install. See ./docs/modules.md for more information on
# what modules are.
#
# The values of this are provided to `yarn add` for inclusion.
modules:
    - "@verji/verji-security-module"
    #- "@verji/verji-usermenu-module"
