# Re-fetches the Jitsi SDK and opens a PR to update it if it's different from what's in the repository
name: Update Jitsi
on:
    workflow_dispatch: {}
    schedule:
        - cron: "0 3 * * 0" # 3am every Sunday
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  cache: "yarn"

            - name: Install Deps
              run: "yarn install --frozen-lockfile"

            - name: Fetch Jitsi
              run: "yarn update:jitsi"

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e # v6
              with:
                  token: ${{ secrets.ELEMENT_BOT_TOKEN }}
                  branch: actions/jitsi-update
                  delete-branch: true
                  title: Jitsi Update
                  labels: |
                      T-Task
